baseURL = "https://practicalgobook.net"
languageCode = "en-us"
title = "Practical Go - Book Website"
theme = "etch"
googleAnalytics = ""
enableGitInfo = true
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
unsafe= true

[params]
  description = "Book website for Practical Go, a book by Amit Saha"
  mainSection = "about"
  showAllPostsOnHomePage = true
  postsOnHomePage = 20 
  tagsOverview = true
  showProjectsList = false
  show_updated = true
  rss = true
  dark = "auto"

[[params.social]]
  name = "github"
  link = "https://github.com/practicalgo"

[[params.social]]
  name = "email"
  link = "mail@practicalgobook.net" # no need for "mailto:" at the start

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Table of Contents"
    url = "/toc"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1


[[menu.main]]
    name = "Buy the book!"
    url = "/buy"
    weight = 1


[[menu.main]]
    name = "Code"
    url = "/code"
    weight = 1

[[menu.main]]
    name = "Support"
    url = "/support"
    weight = 1

[[menu.main]]
    name = "Subscribe (RSS)"
    url = "/index.xml"  
